import ArgumentParser

/// Root command for the Crow CLI.
///
/// All subcommands are registered here. The `@main` entry point in the
/// executable target calls `Crow.main()` to start argument parsing.
public struct CrowCommand: ParsableCommand {
    public static let configuration = CommandConfiguration(
        commandName: "crow",
        abstract: "CLI for Crow — manage sessions, terminals, and metadata",
        version: CLIVersion.version,
        subcommands: [
            Setup.self,
            AutostartCommand.self,
            NewSession.self,
            RenameSession.self,
            SelectSession.self,
            ListSessions.self,
            GetSession.self,
            SetStatus.self,
            SetLocked.self,
            SetPinned.self,
            MarkInReview.self,
            CompleteSession.self,
            SetSessionActive.self,
            MarkIssueDone.self,
            AddMergeLabel.self,
            HandoffAgent.self,
            DeleteSession.self,
            SetTicket.self,
            SetGoal.self,
            WorkOnIssue.self,
            BatchWorkOnIssues.self,
            StartReview.self,
            CreateManager.self,
            RefreshTickets.self,
            QuickActionCmd.self,
            ListTickets.self,
            ListReviews.self,
            Job.self,
            Telemetry.self,
            Cleanup.self,
            UI.self,
            Terminal.self,
            Automation.self,
            Notifications.self,
            Defaults.self,
            Agents.self,
            Workspace.self,
            Corveil.self,
            Gateway.self,
            WebPassword.self,
            Logsync.self,
            Backfill.self,
            MCP.self,
            AddWorktree.self,
            ListWorktrees.self,
            NewTerminal.self,
            ListTerminals.self,
            CloseTerminal.self,
            RecreateTerminal.self,
            RenameTerminal.self,
            Send.self,
            LaunchAgent.self,
            RetryReadiness.self,
            RestartManager.self,
            RestartTmuxServer.self,
            ReloadTmuxConfig.self,
            OpenInVSCode.self,
            OpenTerminal.self,
            AddLink.self,
            ListLinks.self,
            RemoveLink.self,
            EditLink.self,
            TransitionTicket.self,
            ResyncJira.self,
            ListAllowlist.self,
            PromoteAllowlist.self,
            RefreshAllowlist.self,
            GetScorecard.self,
            RebuildScorecard.self,
            GetState.self,
            ListArtifacts.self,
            HookEventCmd.self,
            GenerateDocs.self,
            Version.self,
        ]
    )

    public init() {}
}
