#!/usr/bin/env bash
# Generate CLIVersion.swift with the version string for the `crow` CLI.
#
# Output: Packages/CrowCLI/Sources/CrowCLILib/Generated/CLIVersion.swift
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
CLI_OUTPUT_DIR="$ROOT_DIR/Packages/CrowCLI/Sources/CrowCLILib/Generated"

mkdir -p "$CLI_OUTPUT_DIR"

# Read version: CROW_VERSION env var takes precedence, then VERSION file
if [ -n "${CROW_VERSION:-}" ]; then
    VERSION="$CROW_VERSION"
elif [ -f "$ROOT_DIR/VERSION" ]; then
    VERSION="$(tr -d '[:space:]' < "$ROOT_DIR/VERSION")"
else
    echo "ERROR: No VERSION file found and CROW_VERSION not set" >&2
    exit 1
fi

# Capture git info (fallback to "dev" if not in a git repo)
if git -C "$ROOT_DIR" rev-parse HEAD >/dev/null 2>&1; then
    GIT_SHORT_SHA=$(git -C "$ROOT_DIR" rev-parse --short HEAD)
    BUILD_NUMBER=$(git -C "$ROOT_DIR" rev-list --count HEAD)
else
    GIT_SHORT_SHA="dev"
    BUILD_NUMBER="1"
fi

BUILD_DATE=$(date -u +"%Y-%m-%d")

# Generate CLIVersion.swift for the CLI tool
cat > "$CLI_OUTPUT_DIR/CLIVersion.swift" << EOF
// Auto-generated by scripts/generate-build-info.sh — do not edit
enum CLIVersion {
    static let version = "$VERSION"
}
EOF

echo "Generated CLI version info (version: $VERSION, build: $BUILD_NUMBER, SHA: $GIT_SHORT_SHA, date: $BUILD_DATE)"

# Emit build info for the web UI's Settings → About tab (served at /version.json).
WEB_DIR="$ROOT_DIR/Packages/CrowDaemon/Sources/CrowDaemon/Resources/web"
if [ -d "$WEB_DIR" ]; then
    cat > "$WEB_DIR/version.json" << EOF
{"version": "$VERSION", "gitSha": "$GIT_SHORT_SHA", "buildDate": "$BUILD_DATE"}
EOF
fi
